import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import Header from "@/components/custom/Header";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
      >
        <ConvexClientProvider>
          <Provider>
            <Header />
            {children}
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
